__title__ = '{{cookiecutter.project_slug}}'
__description__ = '{{cookiecutter.project_name}}'
__url__ = 'https://github.com/gramaziokohler/{{cookiecutter.project_slug}}'
__version__ = '{{cookiecutter.version}}'
__author__ = 'Gramazio Kohler Research'
__author_email__ = 'gramaziokohler@arch.ethz.ch'
__license__ = 'MIT license'
__copyright__ = 'Copyright {% now 'utc', '%Y' %} Gramazio Kohler Research'
